### ISSUE TITLE
Require contact information for MatterFi site:

### ISSUE THREAD

**Issue by realrobertdouglas** [matterfi/matterfi.github.io#1]
Email, Address, Social Medias, Phone Numbers.

**Comment by realrobertdouglas** [comment]
**email:** contact@matterfi.com points to a Tim, Mehow, Robert group

**Address:** 30 N Gould St, Ste R
Sheridan , WY 82801

**Social Media:** 

Telegram:
t.me/matterfi

Discord:
discord.gg/RVGfCbZNmG
(FYI a Discord.ME/MatterFi can be made later)

Instagram:
instagram.com/matterfinance
(MatterFi is taken by a black film group “matter Films”

Facebook:
www.facebook.com/MatterFi-108207714429114/s
(URL shortening is not setup yet)

Twitter:
twitter.com/FiMatter (this URL will change after further verification)

LinkedIn:
linkedin.com/company/matterfi

Signal:
Not sure if I can help you here… but I want to!

Phone Numbers:

I need to setup GrassHopper (https://grasshopper.com/) number later, for now if you'll leave it blank I'll add a reminder to follow up

**Comment by realrobertdouglas** [comment]
I'm adding Mehow to this GitHub Org, I'll tag him in this project. @wigggles should you choose the next step is to populate the above information (during normal work hours and do not stress your self)

**Comment by wigggles** [comment]
Can add the company social media links into the Home page bottom "Contact us" section next to the Form.

**Comment by realrobertdouglas** [comment]
To do so we'll need to "hydrate" them with relevant information and bring them up to the same standards as the website. I can backlog this if you see it as valuable? I just don't see it as valuable right now.

**Comment by realrobertdouglas** [comment]
I've moved it to ice box and added a personal reminder to follow up in two months, I'll assign it to my self so you feel no more pressure

**Comment by wigggles** [comment]
I think the color hover icons that jekyll has should take care of most of that. Its got icons for most media already. I don't think it has:
Discord or 
Telegram or 
Linkedin (which also could be used with the Teams bios later)


But there are icons for Twitter, Instagram, Facebook already there.

**Comment by wigggles** [comment]
ok updated font awesome, was required for social media icons discord and telegram. Site has links to all provided media.

**Comment by wigggles** [comment]
We should make sure that these media accounts share a link to the web site to help with SEO

**Comment by wigggles** [comment]
Media accounts are linked on home page.
