### ISSUE TITLE
Change Mehow's BIO

### ISSUE THREAD

**Issue by realrobertdouglas** [matterfi/matterfi.github.io#2]
New bio for Mehow

"When I was younger I worked as a consultant hacking corporate machines, if you think your electronics and financial systems are secure, do I have news for you. Now I’m building technology that eliminates theft and fraud so that these issues can never happen again."

Tim feels as though the old logo:

"When I was younger I worked as a consultant hacking voting machines, if you think your elections are secure, do I have news for you. Now I’m building technology that eliminates theft and fraud so that these issues can never happen again."

Is too political

**Comment by wigggles** [comment]
Updated
